server:
  port: 8080


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root1234
    url: jdbc:mysql://database-1.czamya2yi0yw.ap-northeast-2.rds.amazonaws.com/demo?serverTimezone=Asia/Seoul&characterEncoding=UTF-8

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis

jwt:
  secret: testtestetstesetsetstestetestsetsetse
  access-token-expire-time:  3600000 #1시간
  refresh-token-expire-time: 86400000 #24시간



# Swagger UI의 접근 경로를 설정합니다.
springdoc:
  swagger-ui:
    enabled: true

# Feign Client logging
logging:
  level:
    com.bisise.interviewserver.external.openfeign: debug

openai:
  url: https://api.openai.com/v1/chat/completions
  model: gpt-3.5-turbo
  apikey: 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