server:
  port: 8080


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: potendayjob0322!
    url: jdbc:mysql://jobterviewee.cvquswweky2z.ap-northeast-2.rds.amazonaws.com/jobterviewee?serverTimezone=Asia/Seoul&characterEncoding=UTF-8

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis

jwt:
  secret: testtestetstesetsetstestetestsetsetse
  access-token-expire-time:  3600000 #1시간
  refresh-token-expire-time: 86400000 #24시간



# Swagger UI의 접근 경로를 설정합니다.
springdoc:
  swagger-ui:
    enabled: true
