server:
  port: 8080


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${rds.useraname}
    password: ${rds.password}
    url: ${rds.host}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

jwt:
  secret: ${jwt.secret}
  access-token-expire-time: 60000 #1시간
  refresh-token-expire-time: 86400000 #24시간



# Swagger UI의 접근 경로를 설정합니다.
springdoc:
  swagger-ui:
    enabled: true
