server:
  port: 8080


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${rds.useraname}
    password: ${rds.password}
    url: ${rds.host}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  data:
    redis:
      host: 175.45.193.187
      port: 6379
  cache:
    type: redis

jwt:
  secret: ${jwt.secret}
  access-token-expire-time: 3600000 #1시간
  refresh-token-expire-time: 86400000 #24시간



# Swagger UI의 접근 경로를 설정합니다.
springdoc:
  swagger-ui:
    enabled: true

# Feign Client logging
logging:
  level:
    com.bisise.interviewserver.external.openfeign: debug

openai:
  url: https://api.openai.com/v1/chat/completions
  model: gpt-3.5-turbo
  apikey: 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